version: '3'

services:
  minecraft:
    container_name: mc
    ports:
      - "25565:25565"
    volumes:
      - "vol-minecraft:/data"
    environment:
      EULA: "TRUE"
      MAX_MEMORY: 2G
      MAX_BUILD_HEIGHT: 256
      VIEW_DISTANCE: 15
      LEVEL_TYPE: DEFAULT
      MAX_PLAYERS: 4
      ONLINE_MODE: "FALSE"
      CONSOLE: "false"
    image: itzg/minecraft-server
    restart: always
  # rcon:
  #   image: itzg/rcon
  #   ports:
  #     - "4326:4326"
  #     - "4327:4327"
  #   volumes:
  #     - "rcon:/opt/rcon-web-admin/db"

volumes:
  vol-minecraft:
  # rcon:
